services:
  sql:
    image: pgmp-postgres
    build: ./
    expose:
      - "5432"
    # ports:
    # - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: openchronology
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro

  sql-rest:
    image: postgrest/postgrest:latest
    depends_on:
      - sql
    ports:
      - 3000:3000
    restart: always
    environment:
      PGRST_DB_URI: "postgres://authenticator_user:${PGRST_AUTHENTICATOR_PW}@sql:5432/openchronology"
      PGRST_DB_ANON_ROLE: guest_group
      PGRST_DB_SCHEMAS: api
      PGRST_DB_MAX_ROWS: 10000
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_JWT_AUD: ${PGRST_JWT_AUD}
      PGRST_JWT_ROLE_CLAIM_KEY: ".\"${PGRST_JWT_AUD}/role\""

