services:
  sql:
    image: pgmp-postgres
    build: ./
    # expose:
    #   - "5432"
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: pgmp-test-db
      POSTGRES_PASSWORD: asdf
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro

