[package]
name = "cron-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
reqwest = "0.11.18"
tokio = { version = "1.32.0", features = ["full"] }
